# Problem

Interpret a 2L MLP (one hidden layer) trained to do modular addition.

# Setup
(No need to read)

In [20]:
!git clone https://github.com/ckkissane/mech-interp-practice.git

fatal: destination path 'mech-interp-practice' already exists and is not an empty directory.


In [21]:
# Janky code to do different setup when run in a Colab notebook vs VSCode
DEBUG_MODE = False
try:
    import google.colab
    IN_COLAB = True
    print("Running as a Colab notebook")
    %pip install git+https://github.com/neelnanda-io/TransformerLens.git
    # Install another version of node that makes PySvelte work way faster
    !curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -; sudo apt-get install -y nodejs
    %pip install git+https://github.com/neelnanda-io/PySvelte.git
    # Needed for PySvelte to work, v3 came out and broke things...
    %pip install typeguard==2.13.3
except:
    IN_COLAB = False
    print("Running as a Jupyter notebook - intended for development only!")
    from IPython import get_ipython

    ipython = get_ipython()
    # Code to automatically update the HookedTransformer code as its edited without restarting the kernel
    ipython.magic("load_ext autoreload")
    ipython.magic("autoreload 2")

Running as a Colab notebook
  Cloning https://github.com/neelnanda-io/TransformerLens.git to /tmp/pip-req-build-oljij2i6
  Running command git clone --filter=blob:none --quiet https://github.com/neelnanda-io/TransformerLens.git /tmp/pip-req-build-oljij2i6
  Resolved https://github.com/neelnanda-io/TransformerLens.git to commit 10d2f8a026d73eada861c7d51064f7e24d8f482c
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

## Installing the NodeSource Node.js 16.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 https://deb.nodesource.com/node_16.x jammy InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:6 http://archive.ubuntu.com/ubuntu

In [22]:
# Plotly needs a different renderer for VSCode/Notebooks vs Colab argh
import plotly.io as pio

if IN_COLAB or not DEBUG_MODE:
    # Thanks to annoying rendering issues, Plotly graphics will either show up in colab OR Vscode depending on the renderer - this is bad for developing demos! Thus creating a debug mode.
    pio.renderers.default = "colab"
else:
    pio.renderers.default = "png"

In [23]:
# Import stuff
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import einops
import tqdm.notebook as tqdm
import random
from pathlib import Path
import plotly.express as px
from torch.utils.data import DataLoader

from jaxtyping import Float, Int
from typing import List, Union, Optional
from functools import partial
import copy

import itertools
from transformers import AutoModelForCausalLM, AutoConfig, AutoTokenizer
import dataclasses
from dataclasses import dataclass
import datasets
from IPython.display import HTML

In [24]:
import pysvelte

import transformer_lens
import transformer_lens.utils as utils
from transformer_lens.hook_points import (
    HookedRootModule,
    HookPoint,
)  # Hooking utilities
from transformer_lens import HookedTransformer, HookedTransformerConfig, FactoredMatrix, ActivationCache

Plotting helper functions:

In [25]:
import plotly.graph_objects as go

update_layout_set = {"xaxis_range", "yaxis_range", "hovermode", "xaxis_title", "yaxis_title", "colorbar", "colorscale", "coloraxis", "title_x", "bargap", "bargroupgap", "xaxis_tickformat", "yaxis_tickformat", "title_y", "legend_title_text", "xaxis_showgrid", "xaxis_gridwidth", "xaxis_gridcolor", "yaxis_showgrid", "yaxis_gridwidth"}
def imshow(tensor, renderer=None, xaxis="", yaxis="", **kwargs):
    if isinstance(tensor, list):
        tensor = torch.stack(tensor)
    kwargs_post = {k: v for k, v in kwargs.items() if k in update_layout_set}
    kwargs_pre = {k: v for k, v in kwargs.items() if k not in update_layout_set}
    if "facet_labels" in kwargs_pre:
        facet_labels = kwargs_pre.pop("facet_labels")
    else:
        facet_labels = None
    if "color_continuous_scale" not in kwargs_pre:
        kwargs_pre["color_continuous_scale"] = "RdBu"
    fig = px.imshow(utils.to_numpy(tensor), color_continuous_midpoint=0.0,labels={"x":xaxis, "y":yaxis}, **kwargs_pre).update_layout(**kwargs_post)
    if facet_labels:
        for i, label in enumerate(facet_labels):
            fig.layout.annotations[i]['text'] = label

    fig.show(renderer)

def line(tensor, renderer=None, xaxis="", yaxis="", **kwargs):
    px.line(y=utils.to_numpy(tensor), labels={"x":xaxis, "y":yaxis}, **kwargs).show(renderer)

def scatter(x, y, xaxis="", yaxis="", caxis="", renderer=None, **kwargs):
    x = utils.to_numpy(x)
    y = utils.to_numpy(y)
    px.scatter(y=y, x=x, labels={"x":xaxis, "y":yaxis, "color":caxis}, **kwargs).show(renderer)

def lines(lines_list, x=None, mode='lines', labels=None, xaxis='', yaxis='', title = '', log_y=False, hover=None, **kwargs):
    # Helper function to plot multiple lines
    if type(lines_list)==torch.Tensor:
        lines_list = [lines_list[i] for i in range(lines_list.shape[0])]
    if x is None:
        x=np.arange(len(lines_list[0]))
    fig = go.Figure(layout={'title':title})
    fig.update_xaxes(title=xaxis)
    fig.update_yaxes(title=yaxis)
    for c, line in enumerate(lines_list):
        if type(line)==torch.Tensor:
            line = utils.to_numpy(line)
        if labels is not None:
            label = labels[c]
        else:
            label = c
        fig.add_trace(go.Scatter(x=x, y=line, mode=mode, name=label, hovertext=hover, **kwargs))
    if log_y:
        fig.update_layout(yaxis_type="log")
    fig.show()

def bar(tensor, renderer=None, xaxis="", yaxis="", **kwargs):
    px.bar(
        y=utils.to_numpy(tensor),
        labels={"x": xaxis, "y": yaxis},
        template="simple_white",
        **kwargs).show(renderer)

In [26]:
import transformer_lens.patching as patching
from transformer_lens import evals
import math

In [27]:
def visualize_attn_patterns(heads, local_tokens, local_cache, title: str = ""):
    labels = []
    patterns = []
    batch_index = 0

    for head in heads:
        if isinstance(head, tuple):
            layer, head_index = head
        else:
            layer, head_index = head // model.cfg.n_heads, head % model.cfg.n_heads
        patterns.append(local_cache["pattern", layer][batch_index, head_index])
        labels.append(f"L{layer}H{head_index}")
    patterns = torch.stack(patterns, dim=-1)
    attn_viz = pysvelte.AttentionMulti(tokens=model.to_str_tokens(local_tokens[batch_index]), attention=patterns, head_labels=labels)
    display(HTML(f"<h3>{title}</h3>"))
    attn_viz.show()

# Load Model

This model is a 2L MLP (one hidden layer). An embedding is applied to the inputs (a, b) and these embedding vectors are added before being passed through a standard MLP layer with ReLU activation function:

![picture](https://drive.google.com/uc?id=1mA_0VmZfQ8QnviY8mzuDrss8CXz_iG1g)

It has already been trained and is loaded into this notebook below:

In [28]:
torch.set_grad_enabled(False)

In [29]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [30]:
p = 113
@dataclass
class Config:
    d_model: int = 128
    d_mlp: int = 512
    d_vocab: int = p
    d_vocab_out: int = p
    device: int = device
    seed: int = 0

cfg = Config()
print(cfg)

Config(d_model=128, d_mlp=512, d_vocab=113, d_vocab_out=113, device='cuda', seed=0)


In [31]:
class OneLayerMLP(HookedRootModule):
    def __init__(self, cfg):
        super().__init__()
        torch.manual_seed(cfg.seed)

        self.W_E = nn.Parameter(torch.randn(cfg.d_vocab, cfg.d_model) / np.sqrt(cfg.d_model))
        self.W_in = nn.Parameter(torch.randn(cfg.d_model, cfg.d_mlp) / np.sqrt(cfg.d_model))
        self.W_U = nn.Parameter(torch.randn(cfg.d_mlp, cfg.d_vocab_out) / np.sqrt(cfg.d_mlp))

        self.hook_embed = HookPoint()
        self.hook_pre = HookPoint()
        self.hook_post = HookPoint()

        super().setup()

    def forward(self, data):
        a = data[:, 0]
        b = data[:, 1]
        embed = self.hook_embed(self.W_E[a] + self.W_E[b])
        pre = self.hook_pre(embed @ self.W_in)
        post = self.hook_post(F.relu(pre))
        logits = post @ self.W_U
        return logits

model = OneLayerMLP(cfg).to(cfg.device)
print(model)

OneLayerMLP(
  (hook_embed): HookPoint()
  (hook_pre): HookPoint()
  (hook_post): HookPoint()
)


In [32]:
filename = "mech-interp-practice/models/modular_addition_2l_mlp_model.pt"
state_dict = torch.load(filename)
model.load_state_dict(state_dict, strict=True)

<All keys matched successfully>

# Task description

The model was trained to do modular addition. Given integers (a,b), it computes (a + b) mod p where p=113, and 'a' and 'b' are both integers in the range [0, p-1] inclusive.
The model is given inputs of the form


```
[a, b]
```


Under the hood, both a and b are mapped to embedding vectors and then added together before being inputted into the MLP layer (see the diagram in the 'Load Model' section above). Note this is different from a normal transformer, since the MLP is only applied to one residual stream vector, rather than multiple residual stream vectors for each sequence position.


Below I provide the following datasets that you can use to investigate the model:


* 'dataset' is the full dataset - every possible (a, b) pair. 'labels' are the corresponding answers, a + b mod p, for each pair in 'dataset'
* 'train_data' is the subset of 'dataset' used for training. This was about 30% of the full dataset. 'train_labels' are the corresponding labels.
* 'test_data' consists of the remaining (a,b) pairs in ‘dataset’ not seen during training. 'test_labels' are the corresponding labels.

In [33]:
a_vec = einops.repeat(torch.arange(p), "i -> (i j)", j=p)
print(a_vec.shape)
print(a_vec[:5])

b_vec = einops.repeat(torch.arange(p), "i -> (j i)", j=p)
print(b_vec.shape)
print(b_vec[:5])

dataset = torch.stack([a_vec, b_vec], dim=-1).to(device)
print(dataset.shape)
print(dataset)

torch.Size([12769])
tensor([0, 0, 0, 0, 0])
torch.Size([12769])
tensor([0, 1, 2, 3, 4])
torch.Size([12769, 2])
tensor([[  0,   0],
        [  0,   1],
        [  0,   2],
        ...,
        [112, 110],
        [112, 111],
        [112, 112]], device='cuda:0')


In [34]:
labels = (dataset[:, 0] + dataset[:, 1]) % p
print(labels.shape)
print(labels[:5])

torch.Size([12769])
tensor([0, 1, 2, 3, 4], device='cuda:0')


In [35]:
DATA_SEED = 0
torch.manual_seed(DATA_SEED)

train_frac = 0.3
cutoff = int(train_frac * dataset.shape[0])

indices = torch.randperm(dataset.shape[0])

train_indices = indices[:cutoff]
train_data = dataset[train_indices]
train_labels = labels[train_indices]
print(train_data.shape)
print(train_data[:5])
print(train_labels.shape)
print(train_labels[:5])

test_indices = indices[cutoff:]
test_data = dataset[test_indices]
test_labels = labels[test_indices]
print(test_data.shape)
print(test_data[:5])
print(test_labels.shape)
print(test_labels[:5])

torch.Size([3830, 2])
tensor([[ 37,   1],
        [ 23,   9],
        [  2,  43],
        [  7,  34],
        [ 42, 101]], device='cuda:0')
torch.Size([3830])
tensor([38, 32, 45, 41, 30], device='cuda:0')
torch.Size([8939, 2])
tensor([[ 55,  55],
        [ 69, 109],
        [ 13,  17],
        [103,  54],
        [ 78, 112]], device='cuda:0')
torch.Size([8939])
tensor([110,  65,  30,  44,  77], device='cuda:0')


The model was trained to minimize cross entropy loss. The exact loss function used during training is provided below:

In [36]:
def loss_fn(logits, labels):
    if logits.ndim == 3:
        logits = logits[:, -1, :]
    logits = logits.to(torch.float64)
    log_probs = logits.log_softmax(dim=-1)
    correct_log_probs = log_probs.gather(dim=-1, index=labels[:, None])
    return -correct_log_probs.mean()